Repository xenanetworks/open-automation-python-api, pull requests merged in 2023-04, with the labels that each got.

#126 feat: TX tap autotune in hlfuncs
  docs/source/api_ref/hlfunc/anlt/index.rst
  xoa_driver/__init__.py
  xoa_driver/functions/anlt.py
Labels: feature

#128 feat: Add px_get and px_set in hlfunc
  xoa_driver/functions/anlt_ll_debug.py
Labels: feature

#129 Separate LT algor and im status from anlt_status
  xoa_driver/__init__.py
  xoa_driver/functions/anlt.py
  xoa_driver/functions/tools.py
Labels: improvement

#131 Improve: propagate only xoa warnings
  xoa_driver/__init__.py
  xoa_driver/internals/core/commands/m_commands.py
  xoa_driver/internals/warn.py
  xoa_driver/v2/__init__.py
Labels: improvement

#132 Chimera impairment HLIv2 cleanup
  xoa_driver/internals/hli_v2/ports/port_l23/chimera/pe_distribution.py
  xoa_driver/internals/hli_v2/ports/port_l23/chimera/port_emulation.py
Labels: improvement

#133 Change version to 1.3.0b5
  xoa_driver/__init__.py
Labels: ignore-for-release

#134 Version 1.3.0rc1
  xoa_driver/__init__.py
Labels: ignore-for-release

#136 HLI of PEF_VALUE's protocol_segment_index starts from 1
  xoa_driver/internals/hli_v1/ports/port_l23/chimera/filter_definition/general.py
  xoa_driver/internals/hli_v2/ports/port_l23/chimera/filter_definition/general.py
Labels: bug

#137 Add anlt_strict and anlt_log_control
  docs/source/api_ref/hlfunc/anlt/index.rst
  xoa_driver/__init__.py
  xoa_driver/functions/anlt.py
Labels: feature

#138 Delete not exists field from PEF_TPLDSETTINGS
  xoa_driver/internals/core/commands/pef_commands.py
Labels: bug

#139 Fix px_get
  xoa_driver/__init__.py
  xoa_driver/functions/anlt_ll_debug.py
Labels: ignore-for-release

#140 Add ANEG mode check in an_status
  xoa_driver/functions/anlt.py
  xoa_driver/functions/tools.py
  xoa_driver/internals/core/commands/pl1_commands.py
Labels: improvement

#142 Add xla_dump_ctrl
  xoa_driver/__init__.py
  xoa_driver/functions/anlt_ll_debug.py
Labels: feature

#144 Add four debug hlfuncs for xoa-utils
  xoa_driver/__init__.py
  xoa_driver/functions/anlt_ll_debug.py
Labels: feature

#145 Fix xla_dump_ctrl to serdes 0
  xoa_driver/__init__.py
  xoa_driver/functions/anlt_ll_debug.py
Labels: bug

#146 fix(debug hlfunc): Change debug hlfunc get and set
  xoa_driver/__init__.py
  xoa_driver/functions/anlt_ll_debug.py
Labels: bug
